/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

/**
 *
 * @author Bubu
 */
public class JFRotacion extends javax.swing.JFrame {
    
    Ventana ventana;

    /** Creates new form JFRotacion */
    public JFRotacion() {
        initComponents();
    }
    
    public JFRotacion(Ventana v){
        initComponents();
        ventana = v;
        setLocationRelativeTo(ventana);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinner = new javax.swing.JSpinner();
        slider = new javax.swing.JSlider();
        boton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(spinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 50, -1));

        slider.setMaximum(360);
        slider.setValue(90);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });
        getContentPane().add(slider, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 140, -1));

        boton.setText("OK");
        getContentPane().add(boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        // TODO add your handling code here:
        ///Cuando se cambia el slider se pone número al spinner
        float valor = (float) slider.getValue();
        System.out.println("valor slider= "+valor);
        spinner.setValue(valor);
    }//GEN-LAST:event_sliderStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JSlider slider;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables

}
