package elementos.graficos;

/**
 * @author Lazcano Valdez César Ricardo
 */
public class MatrizPanel extends javax.swing.JPanel {

    private javax.swing.JTextField[][] cTextos;
    
    /**
     * Creates new form MatrizPanel
     */
    public MatrizPanel() {
        initComponents();
        initMatrizVisual();
    }
    
    public void initMatrizVisual(){
        
        cTextos = new javax.swing.JTextField[5][5];
        for(int f = 0; f<5; f++){
            for(int c = 0; c<5; c++){
                cTextos[c][f] = new javax.swing.JTextField();
                cTextos[c][f].setBackground(java.awt.Color.red);
                this.add(cTextos[c][f]);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(300, 300));
        setLayout(new java.awt.GridLayout(5, 5));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
